site_name: Dinorex 's blog
copyright: 'Copyright &copy; 2023 - 2024 Dinorex'
repo_name: 'DINOREXNB.github.io'
repo_url: 'https://github.com/DINOREXNB/DINOREXNB.github.io'

theme:
  logo: https://github.com/DINOREXNB/DINOREXNB.github.io/blob/main/assets/logo.png?raw=true
  name: material
  language: zh
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - navigation.top
    - search.share
    - search.highlight
    - search.suggest
    - navigation.footer
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DINOREXNB
    - icon: fontawesome/brands/qq 
      link: https://user.qzone.qq.com/1819539569
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - md_in_html
  - attr_list
  - toc:
      permalink: true
  - tables
plugins:
  - blog
  - search
nav:
  - About me: index.md
  - 课程笔记:
    - 大二上:
      - 马原: 
        - 马原串讲记录: 马原串讲记录.md
    - 大二下:
      - 近世代数:
        - 集合、映射与变换: 集合、映射与变换.md
        - 代数运算、运算律: 代数运算、运算律.md
  - 比赛:
    - CUPT:
      - CUPT宣讲会: CUPT宣讲会.md 
      - 赛题分析 液滴显微镜: 液滴显微镜.md
      - 校赛总结 液滴显微镜: 液滴显微镜总结.md
      - CUPT培训:
        - 研究题目流程: 研究题目流程.md
        - COMSOL入门: COMSOL.md
        - Tracker入门: Tracker.md
    - 数学建模:
      - 相关基础:
        - 中心差分法: 中心差分法.md
        - 差分方程: 差分方程.md
        - 粒子群优化PSO: 粒子群优化.md
        - 遗传算法GA: 遗传算法.md
        - 灰色与模糊问题: 模糊问题.md
        - 基于熵权法的TOPSIS: topsis.md
      - 数据搜索/绘图网站: data.md
      - 2020国赛A题复现: 
        - 题目: 2020AQ.md
        - Q1: 2020AQ1.md
        - Q2: 2020AQ2.md
        - Q3: 2020AQ3.md
        - Q4: 2020AQ4.md
        - code: 2020Acode.md
        - 碎碎念: 2020Atips.md
      - 2023美赛A题复现:
        - 题目: 2023AQ.md
        - Q1: 2023AQ1.md
        - Q2: 2023AQ2.md
        - Q3: 2023AQ3.md
        - code: 2023Acode.md
      - 2023美赛B题分析: 
        - 题目: 2023mcm.md
        - 相关资料/数据: 2023mcmData.md
        - 探究过程: 2023mcmSol.md
      - 2022美赛B题分析: 2022mcm.md
    - 中学物竞:
      - 物竞心得分享: 物竞心得分享.md